# Generated by Django 3.2.7 on 2021-09-22 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carros',
            name='ano',
        ),
    ]
