# Generated by Django 3.2.7 on 2021-09-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_carros_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=150)),
                ('cnpj', models.IntegerField(max_length=14)),
            ],
        ),
        migrations.DeleteModel(
            name='Carros',
        ),
    ]
